name: jobhub
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  http: ^1.1.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.1.1+1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  uuid: ^4.1.0
  intl: ^0.18.1
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
